### PR TITLE
External-dns: added variable and new file for cloudtrail logging

### PR DESCRIPTION
**Pull request by garegintamrazyan07**
- added variable to enable Cloudtrail
- added new file with resourses to enable logging

issue #139

### CODE REVIEW

**Review by akastav — COMMENTED** [review]
External-dns can enable route53 logs? It no makes sense because we can skip installing external-dns but deploy route53, or external-dns can work with external DNS service like a cloudflare

**Comment by garegintamrazyan07** [comment]
So what you say is that this PR is not needed at all ?

**Comment by akastav** [comment]
> So what you say is that this PR is not needed at all ?

We need to logging and audit route53 but not here, maybe a good point it creates route53 as a module, not just a resource in the example? Add different modes to deploy route53 like a geolocation route or as mirror\proxy mode to external DNS, I don't know, we can talk about it in discussions or offline. Also, it's will be good if we can choose route53 or another cloud DNS (for GCP or Azure)

**Comment by garegintamrazyan07** [comment]
I believe we can create separate issue for that.

**Comment by garegintamrazyan07** [comment]
closing this PR , will discuss route53 topic further

**Pull request closed without merging**
